name: 'setup all the things'
description: setup python packages etc for a workflow
#inputs:
#outputs:
runs:
  using: composite
  steps:
    - name: Create venv
      run: /usr/bin/python3.10 -m venv venv
      shell: bash
    - name: Upgrade pip
      run: |
        . venv/bin/activate
        pip install -U pip
      shell: bash
    - name: Install python requirements
      run: |
        . venv/bin/activate
        pip install -r requirements.txt
      shell: bash
